### ISSUE TITLE
channel_scp_u 文件的错误

### ISSUE THREAD

**Issue by xiwuou** [1148118271/ssh-rs#16]
第24行，

`log::info!("start to upload files, \
        local [{}] files will be synchronized to the remote [{}] folder.", remote_path_str，local_path_str);` 

local_path_str，remote_path_str 位置写反了。

**Comment by 1148118271** [comment]
代码已合并，非常感谢您的帮助。

local_path_str，remote_path_str 中间的逗号您改成了中文逗号了，编译器会报错， 我已经改成英文的了。

![image](https://user-images.githubusercontent.com/56823989/189035047-02f15202-51f6-499f-9bb5-b9e92eaff28f.png)

**Comment by xiwuou** [comment]
emm……，我也粗心了

**Comment by 1148118271** [comment]
哈哈 没事的
