### ISSUE TITLE
Problem with minimum libc version

### ISSUE THREAD

**Issue by Paulo-21** [1148118271/ssh-rs#19]
Hey, i got this error with your library, could we do something to make my program work on my relatively old computer ?

It seems that i only have libc 2.23

i precise that i cant perform upgarde on my machine

```
./client: /lib/i386-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./client)
./client: /lib/i386-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./client)
./client: /lib/i386-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./client)
./client: /lib/i386-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./client)

```
Thank you

**Comment by Paulo-21** [comment]
Sorry, i'm new to rust and computer 
I solved the problem by statically building libc

`RUSTFLAGS='-C target-feature=+crt-static' cargo build --release --target i686-unknown-linux-gnu`
Have a good day and great work !

**Comment by 1148118271** [comment]
Thank you for your blessings and I wish you a happy life.
