### ISSUE TITLE
Looping ssh connection Timeout

### ISSUE THREAD

**Issue by Paulo-21** [1148118271/ssh-rs#20]
Hey, i was wondoring if it could possible to do that, because i'm encounring difficuties.
The first connection connects successfully but all subsequent connections return an error on session.connect()

if i do session.connect().unwrap() :
`thread 'main' panicked at 'called "Result::unwrap()" on an "Err" value: Error: { Kind(Timeout), Message(time out.) }`

{ Kind(Timeout) }

```
loop {
  let mut session: Session = ssh::create_session();
  session.set_timeout(3);
  session.set_user_and_password("user", "password");
  match session.connect("127.0.0.1:22") {
         Ok(_res) => {
              //Do something
         },
         Err(_err) => {
              //handle error
        }
  }
session.close().unwrap();
}
```
Thank you

**Comment by r3dlight** [comment]
Same issue here with ssh-rs = "0.2.0".
Not using it in a loop but I get these timeout messages as well.
Bad packets received in my SSH server logs.

**Comment by 1148118271** [comment]
Sorry, I have a problem with my code and I need to fix it, thank you very much for your feedback.

**Comment by r3dlight** [comment]
No problem, thank you for your work ! Keep us in touch :)

**Comment by Paulo-21** [comment]
Yeah no problemo amigo, nice work anyway :)

**Comment by Paulo-21** [comment]
Did you plan to release an 0.2.1 version ?
Thank you for your reactivitie

**Comment by 1148118271** [comment]
Yes, it is expected to be released in the next few days.

**Comment by 1148118271** [comment]
v0.2.1 released

**Comment by r3dlight** [comment]
It seems to work for me, thank you !

**Comment by Paulo-21** [comment]
Updated, thank you !
