### ISSUE TITLE
Add hmac-sha256 and hmac-512

### ISSUE THREAD

**Issue by r3dlight** [1148118271/ssh-rs#24]
Hi Kang,

Would it be possible to add hmac-sha256 and hmac-sha512 support ? As far as I see, you are only supporting hmac-sha1 for now.

Thank you !

**Comment by 1148118271** [comment]
OK, I'll add support for both algorithms soon.

**Comment by 1148118271** [comment]
> 您在该库上的工作是否有机会使用这些算法？
> 
> 描述 DH 算法匹配失败，服务器支持的算法：diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,客户端支持的算法：curve25519-sha256,ecdh-sha2-nistp256

----
Will try to add these algorithms in the future.

**Comment by r3dlight** [comment]
Great thanks !
