### ISSUE TITLE
[Bug] Can't use example to connect to sshd server: key exchange error.

### ISSUE THREAD

**Issue by qy513314** [1148118271/ssh-rs#34]
Hi,
I used example to connect to sshd server. but it show "key exchange error."

code (home/workspace/ssh-rs/examples/exec):
`use ssh_rs::ssh;

fn main() {
    let mut session = ssh::create_session();
    session.set_user_and_password("root", "P@ssw0rd");
    session.connect("192.168.101.136:22").unwrap();
    // Usage 1
    let exec = session.open_exec().unwrap();
    let vec: Vec<u8> = exec.send_command("ls -all").unwrap();
    println!("{}", String::from_utf8(vec).unwrap());
    // Usage 2
    let channel = session.open_channel().unwrap();
    let exec = channel.open_exec().unwrap();
    let vec: Vec<u8> = exec.send_command("ls -all").unwrap();
    println!("{}", String::from_utf8(vec).unwrap());
    // Close session.
    session.close().unwrap();
}`

[root@codeworkspace exec]#
[root@codeworkspace src]# cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
     Running `/home/workspace/ssh-rs/examples/exec/target/debug/exec`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error: { Kind(SshError("key exchange error.")), Message(key exchange error.) }', src/main.rs:6:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

sshd server info:
`
[root@localhost ~]# cat /etc/*release
CentOS release 6.5 (Final)
LSB_VERSION=base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-n
CentOS release 6.5 (Final)
CentOS release 6.5 (Final)
[root@localhost ~]# rpm -qa | grep ssh
libssh2-1.4.2-1.el6.x86_64
openssh-askpass-5.3p1-94.el6.x86_64
openssh-clients-5.3p1-94.el6.x86_64
openssh-5.3p1-94.el6.x86_64
openssh-server-5.3p1-94.el6.x86_64
`

i capture pcap package in sshd server，it will attach in this web。 filter rule： ip.addr == 192.168.101.136

**Comment by qy513314** [comment]
[sshd_config.txt](https://github.com/1148118271/ssh-rs/files/9948754/sshd_config.txt)

**Comment by qy513314** [comment]
[eth2_2022_11_07_2059.zip](https://github.com/1148118271/ssh-rs/files/9948762/eth2_2022_11_07_2059.zip)

**Comment by qy513314** [comment]
I guess ssh-rs can not support default algorithms on centos 6

**Comment by 1148118271** [comment]
This should be the reason.
you can use `ssh::is_enable_log(true);` to enable the log.
Check whether the server's key exchange algorithm matches the client's algorithm.

Similar to this:

![Dingtalk_20221107154622](https://user-images.githubusercontent.com/56823989/200254056-d67459b9-58d9-4dce-9c4d-f90051d270ac.jpg)

**Comment by HsuJv** [comment]
Referring to 
https://github.com/openssh/openssh-portable/blob/V_5_3/kex.h#L35-L38,
OpenSSH server v5.3 doesn't look like it supports the kex algorithm we need

**Comment by HsuJv** [comment]
Maybe can close as duplicate to #24
