### ISSUE TITLE
ssh-ed25519

### ISSUE THREAD

**Issue by wangbokun** [1148118271/ssh-rs#40]
[delete ssh-ed25519 加密](https://github.com/1148118271/ssh-rs/commit/68f0d282165669d067d990915a66f09c82f01c59)
貌似我的服务器上不能decode ed25519 加密. 注释之后，登录可用. 不清楚是什么原因

**Comment by HsuJv** [comment]
ed25519需要`ssh-keygen -t ed25519`生成的私钥，这个支持目前进行中

**Comment by HsuJv** [comment]
Yes there was a bug that I forgot to change the priority of public key algorithms based on the input private key type

**Comment by wangbokun** [comment]
nice!
