### ISSUE TITLE
`connect(..)` does not timeout

### ISSUE THREAD

**Issue by andresv** [1148118271/ssh-rs#57]
When connecting to a host that is not responding `connect(..)` never times out.
Tried with this: https://github.com/1148118271/ssh-rs/blob/main/examples/exec/src/main.rs also added `timeout(1000)`.

```rust
use ssh_rs::ssh;

fn main() {
    ssh::enable_log();

    let mut session = ssh::create_session()
        .username("ubuntu")
        .password("password")
        .timeout(1000)
        .connect("192.168.1.52:22")
        .unwrap()
        .run_local();

    let exec = session.open_exec().unwrap();
    let vec: Vec<u8> = exec.send_command("ls -all").unwrap();
    println!("{}", String::from_utf8(vec).unwrap());
    // Close session.
    session.close();
}

```

**Comment by andresv** [comment]
Blocking `connect` is used here: https://github.com/1148118271/ssh-rs/blob/main/src/session/mod.rs#L249 instead of [connect_timeout](https://doc.rust-lang.org/std/net/struct.TcpStream.html#method.connect_timeout).

**Comment by HsuJv** [comment]
@andresv  Yes, you are right. That should be an issue. Appreciate your help

**Comment by andresv** [comment]
Created PR https://github.com/1148118271/ssh-rs/pull/58.
