### ISSUE TITLE
Add timeout support for read operation

### ISSUE THREAD

**Issue by laeo** [1148118271/ssh-rs#6]
I'v read your sample code, the read operation seems not non-blocking, so the code will stuck there. You could have to add timeout support for it, hence the code can be executed until the end.

**Comment by 1148118271** [comment]
Ok, I will add the function of reading timeout in non-blocking case as soon as possible, thank you very much for your valuable comments.😁

**Comment by 1148118271** [comment]
> I'v read your sample code, the read operation seems not non-blocking, so the code will stuck there. You could have to add timeout support for it, hence the code can be executed until the end.

Ok, I will add the function of reading timeout in non-blocking case as soon as possible, thank you very much for your valuable comments.😁

**Comment by 1148118271** [comment]
Timeout handling has been added and will be released in the next version.
