### ISSUE TITLE
add more encryption algorithms

### ISSUE THREAD

**Issue by zero-github** [1148118271/ssh-rs#68]
my ssh server only support the below encryption algorithms, but the library do not support, 
could you please add these implementation or give me an example for one of them.
["aes128-cbc", "3des-cbc", "aes192-cbc", "aes256-cbc"]

**Comment by HsuJv** [comment]
Will do this ASAP.
BRs.

**Comment by HsuJv** [comment]
Hi there,

Pr #73 has already implemented the four algorithms

Note that there are some breaking APIs as the version number is grown up.

BRs

**Comment by HsuJv** [comment]
Usage:
https://github.com/1148118271/ssh-rs/blob/fc7a5202c6f60e50fbabd362449a0b307a8be4fe/tests/algorithms.rs#L149-L217
