### ISSUE TITLE
Bump ssh-key crate version

### ISSUE THREAD

**Issue by r3dlight** [1148118271/ssh-rs#70]
Hi,

Can you bump at least ssh-key version to "0.6" ?
ssh-key depends on ed25519-dalek : 
https://rustsec.org/advisories/RUSTSEC-2022-0093.html

Thanks :)

**Comment by HsuJv** [comment]
Sure, will do this asap

**Comment by r3dlight** [comment]
Hi,
I already made the modifications and if you want me to, I can make a PR : https://github.com/r3dlight/ssh-rs
Nevertheless, aes crate is still  "0.7" because of the ctr feature (deprecated in 0.8.x series)
Let me know :)

**Comment by HsuJv** [comment]
LGTM, you can file a PR so that I can make the workflow run.
BRs

**Comment by HsuJv** [comment]
Close as #71 is done
