### ISSUE TITLE
Error when connecting to older ExtremeXOS switch

### ISSUE THREAD

**Issue by cchance27** [1148118271/ssh-rs#80]
I've enabled all the deprecated features, but when i use the following connection

```    let mut session = ssh::create_session()
        .username(values[4])
        .password(values[5])
        .add_pubkey_algorithms(algorithm::PubKey::SshRsa)
        .add_kex_algorithms(algorithm::Kex::DiffieHellmanGroup1Sha1)
        .add_mac_algortihms(algorithm::Mac::HmacSha1)
        .connect(format!("{}:22", values[3]))
        .expect("Unable to connect to SSH")
        .run_local();
```

I get the following, which is odd it seems like the server has no response? I can connect to it with old versions of putty.

I think this might be because of an outdated pubkey algorithm that isn't supported "ssh-dss"?

ERROR ssh::config::algorithm: err_msg: "Key_agreement: the signature algorithm fails to match, algorithms supported by the server: ,algorithms supported by the client: rsa-sha2-512,rsa-sha2-256,ssh-rsa"

**Comment by HsuJv** [comment]
Hi,

`ssh-dss` is not listed as a supported algorithm currently.
You can bump the log level to "INFO", showing the `original` cypher list that the server returns.
The error message only shows the after-modifying cypher list, which by design can only list the algorithms we supported.

BRs.
