### ISSUE TITLE
Use Rust std TCP set_read_TimeOut instead of a custum one ?

### ISSUE THREAD

**Issue by Paulo-21** [1148118271/ssh-rs#87]
Hey,
I would like to talk about the way you handle the timeout when reading stuff on the tcp connection.

I was wondering if it would be better to use the standard implementation for read with a timeout on TCP rather than a custum one.
https://doc.rust-lang.org/std/net/struct.TcpStream.html#method.set_read_timeout

I m asking my self if your implementation can cause an unnecessary hight CPU usage if the server respond slowly.

https://github.com/1148118271/ssh-rs/blob/9f3528da02ad2920a29acc88308932ee7f70046a/src/model/packet.rs#L52

The tcp connection is set by default to non blocking :
https://github.com/1148118271/ssh-rs/blob/9f3528da02ad2920a29acc88308932ee7f70046a/src/session/mod.rs#L255

So when you read 
https://github.com/1148118271/ssh-rs/blob/9f3528da02ad2920a29acc88308932ee7f70046a/src/model/packet.rs#L61

The read call terminates immediately if nothing is available at the moment, returning the wouldBlock error, then the loop checks the timeout and loops indefinitely until something is available in the buffer.

It might be more efficient to read only once and let the system manage the timeout ?

What do you think about ?
Because when i connect to my server, i notice an hight cpu usage from my program who use only your lib.

**Comment by HsuJv** [comment]
I totally agree with that.

But the key is, that the underlying packet processing is performed on any trait that implements `Read`, ie `BufReader`, `TcpStream`, `SslStream`, `WebSocketStream` and so on.
I'm not quite sure if optimising for TCP only is sensible.

Anyway, I can do some investigation when I'm free.
Also, any suggestions are welcome.

BRs.

**Comment by Paulo-21** [comment]
Yes, I understand, does the library support or would like another protocol than ssh over tcp?
Mio is for non-blocking IO.
IMO ssh-rs doesn't need to use non-blocking IO calls.
Non-blocking IO is when you want to do things but you're blocked because there's no data available at the time.
As I read it, the library does nothing instead of checking its client's timeout.

I did something experimental, I got a huge improvement in CPU usage from 100% to 0.1%.

You check with 
`ssh-rs = { git = "https://github.com/Paulo-21/ssh-rs.git", branch = "main" }` 
https://github.com/Paulo-21/ssh-rs/commit/f75415f85dea93b6e6c6bbf9d11daab17f61e6c5

Just removing the non blocking by default and set the default timeout to 30 sec with the standard function.

What do you think about ?

**Comment by HsuJv** [comment]
Hi, 
I finally fix this high CPU usage via another way 
https://github.com/1148118271/ssh-rs/commit/567a88ef3b62e2c410ba2e906b9b12040f3d4fd0
which can also make the CPU down to about 0.1-0.5%

And regarding your question:
```
does the library support or would like another protocol than ssh over TCP?
```
The answer is Yes. Not only in the WebSocket (In plans), but also in some of my private repos I use it to playback recorded ssh traffic via bufReader
